### ISSUE TITLE
Bug: Plugin doesn't error out the pipeline on errors

### ISSUE THREAD

**Issue by wass3r** [go-vela/vela-artifactory#44]
```
[Error] [Thread 2] Artifactory response: 409 Conflict
[Error] Failed uploading 1 artifacts.
```

this example output would still leave the step it was used on as a successful step

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
